# Used Car Price Prediction

### Importing required libraries

In [139]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

### Loading data

In [140]:
df = pd.read_csv("D:/Code/Projects/Used_Car_Price/Dataset/used_car_dataset.csv")
df

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"
...,...,...,...,...,...,...,...,...,...,...,...
9577,Skoda,Octavia,2014,10,"105,904 km",Automatic,second,Diesel,Oct-24,"Skoda Octavia 1.9 Elegance TDI, 2014, Diesel","₹ 10,40,000"
9578,Maruti Suzuki,Alto-800,2020,4,"55,000 km",Manual,first,Hybrid/CNG,Nov-24,"Maruti Suzuki Alto 800 CNG LXI Optional, 2020,...","₹ 3,75,000"
9579,Maruti Suzuki,Ritz,2013,11,"92,000 km",Manual,first,Diesel,Nov-24,"Maruti Suzuki Ritz VDi, 2013, Diesel","₹ 4,15,000"
9580,Hyundai,Verna,2019,5,"72,000 km",Automatic,first,Petrol,Oct-24,"Hyundai Verna VTVT 1.6 AT SX Option, 2019, Petrol","₹ 8,55,000"
9581,Hyundai,New i20,2021,3,"83,228 km",Manual,second,Petrol,Nov-24,"Hyundai New i20 1.2 Asta IVT, 2021, Petrol","₹ 6,99,000"

### EDA

In [141]:
df.isna().sum()

Brand            0
model            0
Year             0
Age              0
kmDriven        47
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [142]:
# Dropping rows with null value

df = df.dropna(axis=0)
df

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"
...,...,...,...,...,...,...,...,...,...,...,...
9577,Skoda,Octavia,2014,10,"105,904 km",Automatic,second,Diesel,Oct-24,"Skoda Octavia 1.9 Elegance TDI, 2014, Diesel","₹ 10,40,000"
9578,Maruti Suzuki,Alto-800,2020,4,"55,000 km",Manual,first,Hybrid/CNG,Nov-24,"Maruti Suzuki Alto 800 CNG LXI Optional, 2020,...","₹ 3,75,000"
9579,Maruti Suzuki,Ritz,2013,11,"92,000 km",Manual,first,Diesel,Nov-24,"Maruti Suzuki Ritz VDi, 2013, Diesel","₹ 4,15,000"
9580,Hyundai,Verna,2019,5,"72,000 km",Automatic,first,Petrol,Oct-24,"Hyundai Verna VTVT 1.6 AT SX Option, 2019, Petrol","₹ 8,55,000"
9581,Hyundai,New i20,2021,3,"83,228 km",Manual,second,Petrol,Nov-24,"Hyundai New i20 1.2 Asta IVT, 2021, Petrol","₹ 6,99,000"

In [143]:
df.isna().sum()

Brand           0
model           0
Year            0
Age             0
kmDriven        0
Transmission    0
Owner           0
FuelType        0
PostedDate      0
AdditionInfo    0
AskPrice        0
dtype: int64

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9535 entries, 0 to 9581
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9535 non-null   object
 1   model         9535 non-null   object
 2   Year          9535 non-null   int64
 3   Age           9535 non-null   int64
 4   kmDriven      9535 non-null   object
 5   Transmission  9535 non-null   object
 6   Owner         9535 non-null   object
 7   FuelType      9535 non-null   object
 8   PostedDate    9535 non-null   object
 9   AdditionInfo  9535 non-null   object
 10  AskPrice      9535 non-null   object
dtypes: int64(2), object(9)
memory usage: 893.9+ KB

In [145]:
# Removing ₹ sign
df['AskPrice'] = df['AskPrice'].str.replace('₹', '', regex=False)
# Removing commas
df['AskPrice'] = df['AskPrice'].str.replace(',', '', regex=False)
# Convert to int
df['AskPrice'] = df['AskPrice'].astype(int)

In [146]:
# Removing km
df['kmDriven'] = df['kmDriven'].str.replace('km', '', regex=False)
# Removing commas
df['kmDriven'] = df['kmDriven'].str.replace(',', '', regex=False)
# Comvert to int
df['kmDriven'] = df['kmDriven'].astype(float)

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9535 entries, 0 to 9581
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9535 non-null   object
 1   model         9535 non-null   object
 2   Year          9535 non-null   int64
 3   Age           9535 non-null   int64
 4   kmDriven      9535 non-null   float64
 5   Transmission  9535 non-null   object
 6   Owner         9535 non-null   object
 7   FuelType      9535 non-null   object
 8   PostedDate    9535 non-null   object
 9   AdditionInfo  9535 non-null   object
 10  AskPrice      9535 non-null   int64
dtypes: float64(1), int64(3), object(7)
memory usage: 893.9+ KB

In [148]:
# Changing Age from years to month for better accuracy
df['Age'] = df['Age']*12
df

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,276,98000.0,Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...",195000
1,Toyota,Innova,2009,180,190000.0,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...",375000
2,Volkswagen,VentoTest,2010,168,77246.0,Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...",184999
3,Maruti Suzuki,Swift,2017,84,83500.0,Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,565000
4,Maruti Suzuki,Baleno,2019,60,45000.0,Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol",685000
...,...,...,...,...,...,...,...,...,...,...,...
9577,Skoda,Octavia,2014,120,105904.0,Automatic,second,Diesel,Oct-24,"Skoda Octavia 1.9 Elegance TDI, 2014, Diesel",1040000
9578,Maruti Suzuki,Alto-800,2020,48,55000.0,Manual,first,Hybrid/CNG,Nov-24,"Maruti Suzuki Alto 800 CNG LXI Optional, 2020,...",375000
9579,Maruti Suzuki,Ritz,2013,132,92000.0,Manual,first,Diesel,Nov-24,"Maruti Suzuki Ritz VDi, 2013, Diesel",415000
9580,Hyundai,Verna,2019,60,72000.0,Automatic,first,Petrol,Oct-24,"Hyundai Verna VTVT 1.6 AT SX Option, 2019, Petrol",855000
9581,Hyundai,New i20,2021,36,83228.0,Manual,second,Petrol,Nov-24,"Hyundai New i20 1.2 Asta IVT, 2021, Petrol",699000

In [149]:
# Dropping unnecessary columns
df = df.drop(['Year', 'PostedDate', 'AdditionInfo'], axis=1)
df

,Brand,model,Age,kmDriven,Transmission,Owner,FuelType,AskPrice
0,Honda,City,276,98000.0,Manual,second,Petrol,195000
1,Toyota,Innova,180,190000.0,Manual,second,Diesel,375000
2,Volkswagen,VentoTest,168,77246.0,Manual,first,Diesel,184999
3,Maruti Suzuki,Swift,84,83500.0,Manual,second,Diesel,565000
4,Maruti Suzuki,Baleno,60,45000.0,Automatic,first,Petrol,685000
...,...,...,...,...,...,...,...,...
9577,Skoda,Octavia,120,105904.0,Automatic,second,Diesel,1040000
9578,Maruti Suzuki,Alto-800,48,55000.0,Manual,first,Hybrid/CNG,375000
9579,Maruti Suzuki,Ritz,132,92000.0,Manual,first,Diesel,415000
9580,Hyundai,Verna,60,72000.0,Automatic,first,Petrol,855000
9581,Hyundai,New i20,36,83228.0,Manual,second,Petrol,699000

In [150]:
df = df.rename(columns={'model':'Model'})
df = df.rename(columns={'kmDriven':'KmDriven'})

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9535 entries, 0 to 9581
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9535 non-null   object
 1   Model         9535 non-null   object
 2   Age           9535 non-null   int64
 3   KmDriven      9535 non-null   float64
 4   Transmission  9535 non-null   object
 5   Owner         9535 non-null   object
 6   FuelType      9535 non-null   object
 7   AskPrice      9535 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 670.4+ KB

In [152]:
df.duplicated().sum()

np.int64(820)

In [153]:
# Dropping duplicate values

df = df.drop_duplicates()
df

,Brand,Model,Age,KmDriven,Transmission,Owner,FuelType,AskPrice
0,Honda,City,276,98000.0,Manual,second,Petrol,195000
1,Toyota,Innova,180,190000.0,Manual,second,Diesel,375000
2,Volkswagen,VentoTest,168,77246.0,Manual,first,Diesel,184999
3,Maruti Suzuki,Swift,84,83500.0,Manual,second,Diesel,565000
4,Maruti Suzuki,Baleno,60,45000.0,Automatic,first,Petrol,685000
...,...,...,...,...,...,...,...,...
9576,Porsche,Cayenne,12,7700.0,Automatic,first,Petrol,13600000
9578,Maruti Suzuki,Alto-800,48,55000.0,Manual,first,Hybrid/CNG,375000
9579,Maruti Suzuki,Ritz,132,92000.0,Manual,first,Diesel,415000
9580,Hyundai,Verna,60,72000.0,Automatic,first,Petrol,855000
9581,Hyundai,New i20,36,83228.0,Manual,second,Petrol,699000

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8715 entries, 0 to 9581
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         8715 non-null   object
 1   Model         8715 non-null   object
 2   Age           8715 non-null   int64
 3   KmDriven      8715 non-null   float64
 4   Transmission  8715 non-null   object
 5   Owner         8715 non-null   object
 6   FuelType      8715 non-null   object
 7   AskPrice      8715 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 612.8+ KB

### Encoding

In [155]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['Brand'] = encoder.fit_transform(df['Brand'])
df['Model'] = encoder.fit_transform(df['Model'])
df['Transmission'] = encoder.fit_transform(df['Transmission'])
df['Owner'] = encoder.fit_transform(df['Owner'])
df['FuelType'] = encoder.fit_transform(df['FuelType'])

In [156]:
df

      Brand  Model  Age  KmDriven  Transmission  Owner  FuelType  AskPrice
0        12     84  276   98000.0             1      1         2    195000
1        35    187  180  190000.0             1      1         0    375000
2        36    345  168   77246.0             1      0         0    184999
3        22    316   84   83500.0             1      1         0    565000
4        22     52   60   45000.0             0      0         2    685000
...     ...    ...  ...       ...           ...    ...       ...       ...
9576     29     76   12    7700.0             0      0         2  13600000
9578     22     40   48   55000.0             1      0         1    375000
9579     22    276  132   92000.0             1      0         0    415000
9580     13    350   60   72000.0             0      0         2    855000
9581     13    236   36   83228.0             1      1         2    699000

[8715 rows x 8 columns]

### Splitting into Train, Test

In [157]:
from sklearn.model_selection import train_test_split

x = df.drop('AskPrice', axis=1)
y = df['AskPrice']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print("Training set shape:", x_train.shape)
print("Testing set shape:", x_test.shape)

Training set shape: (6972, 7)
Testing set shape: (1743, 7)

In [158]:
x_train

      Brand  Model  Age  KmDriven  Transmission  Owner  FuelType
8893     20    174   48   48000.0             0      0         2
3439     13    100   60   47000.0             0      0         0
303      13    392   84   95000.0             1      1         2
4235     36    253   72   78000.0             0      1         2
7504     13    122   84   24200.0             0      1         1
...     ...    ...  ...       ...           ...    ...       ...
4546     22     52   72   65000.0             0      1         1
3271     15    131   72   57900.0             0      1         0
7502     22    116   48   36000.0             0      0         1
6342     13    168   84   42568.0             1      0         2
1613     34    176   84   98623.0             0      0         0

[6972 rows x 7 columns]

### Model Training & Evaluation

#### Model Evaluation

In [159]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

def metric_calc(x, y):
    y_pred = model.predict(x)
    y_true = y
    
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = root_mean_squared_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    # adjusted r2
    # number of values in the data set
    n = y_true.size
    # number of independent features
    k = 7
    adjusted_r2 = 1 - ((1-r2) * ((n - 1) / (n - (k + 1))))
    adjusted_r2
    
    print(f"Metrics:\n mae = {mae}\n mse = {mse}\n rmse = {rmse}\n r2 = {r2}\n adjusted_r2 = {adjusted_r2}")

### Linear Regression

In [160]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [161]:
# training accuracy
y_pred = model.predict(x_train)
y_true = y_train

print(f"Training")
metric_calc(y_pred, y_true)

# testing accuracy
y_pred = model.predict(x_test)
y_true = y_test

print(f"Testing")
metric_calc(y_pred, y_true)

Training
Metrics:
 mae = 675486.4961654162
 mse = 2265766015042.6436
 rmse = 1505246.1642677067
 r2 = 0.17706047374449163
 adjusted_r2 = 0.176233280079387
Testing
Metrics:
 mae = 701258.9775138886
 mse = 2146490888409.4768
 rmse = 1465090.7440870265
 r2 = 0.20676278869496645
 adjusted_r2 = 0.20356240801534953

### Random Forest

In [162]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [163]:
# training accuracy
y_pred = model.predict(x_train)
y_true = y_train

print(f"Training")
metric_calc(y_pred, y_true)

# testing accuracy
y_pred = model.predict(x_test)
y_true = y_test

print(f"Testing")
metric_calc(y_pred, y_true)

Training
Metrics:
 mae = 102353.47572481733
 mse = 150725449693.5668
 rmse = 388233.7565096147
 r2 = 0.9452556312779112
 adjusted_r2 = 0.9452006039113038
Testing
Metrics:
 mae = 293080.55412737944
 mse = 770069452934.0929
 rmse = 877536.0123288918
 r2 = 0.7154202942788808
 adjusted_r2 = 0.7142721340828877